import type { Post } from "@/lib/posts";

export const externalPosts: Post[] = [
  {
    title: "Hotwire @ Skroutz: Lazy load data with minimum effort",
    date: "2021-07-11",
    summary:
      "Using Hotwire to lazy load data on a page without writing boilerplate code.",
    url: "https://engineering.skroutz.gr/blog/using_hotwire_to_lazy_load_data/",
    source: "Skroutz Engineering",
  },
  {
    title: "Refactoring a React app to progressively load its data",
    date: "2021-04-07",
    summary:
      "Refactoring a React app to show a friendlier UI while its data is still loading.",
    url: "https://engineering.skroutz.gr/blog/refactor-react-app-to-progressively-load-its-data/",
    source: "Skroutz Engineering",
  },
  {
    title:
      "When to Use NoSQL vs SQL: The Ultimate Guide for Choosing a Database",
    date: "2021-03-16",
    summary:
      "How SQL and NoSQL databases differ, and when to choose each for a project.",
    url: "https://www.scalablepath.com/back-end/sql-vs-nosql",
    source: "Scalable Path",
  },
  {
    title: "TypeScript or Flow: Which Is Better?",
    date: "2020-07-16",
    summary:
      "The pros and cons of Flow and TypeScript, to help choose a type checker for a JavaScript project.",
    url: "https://www.scalablepath.com/blog/typescript-or-flow-which-is-better/",
    source: "Scalable Path",
  },
  {
    title: "Including files created by Node.js into .Net project 🛠",
    date: "2020-02-21",
    summary:
      "Adding files generated by a Node.js script to a .NET project file automatically.",
    url: "https://dev.to/kapantzak/including-files-created-by-node-js-into-net-project-l1m",
    source: "DEV.TO",
  },
  {
    title: "Automating boilerplate code generation with Node.js and Handlebars",
    date: "2020-02-18",
    summary:
      "Generating the repetitive files every new form needs with a Node.js script and Handlebars templates.",
    url: "https://dev.to/kapantzak/automating-boilerplate-code-generation-with-node-js-and-handlebars-2c09",
    source: "DEV.TO",
  },
  {
    title: "CSS cascade: Importance",
    date: "2019-12-04",
    summary:
      "How the CSS cascade decides which declaration wins when origins and !important collide.",
    url: "https://dev.to/kapantzak/css-cascade-importance-2g3k",
    source: "DEV.TO",
  },
  {
    title: "JS illustrated: Promises",
    date: "2019-10-08",
    summary: "An illustrated walkthrough of how JavaScript promises work.",
    url: "https://dev.to/kapantzak/js-illustrated-promises-3ign",
    source: "DEV.TO",
  },
  {
    title: "The RGB split effect with css and a bit of javascript",
    date: "2019-09-16",
    summary:
      "Recreating an RGB split text effect with CSS and a little JavaScript.",
    url: "https://dev.to/kapantzak/the-rgb-split-effect-with-css-and-a-bit-of-javascript-4j4i",
    source: "DEV.TO",
  },
  {
    title: "Creating the typewriter effect with the use of async generators",
    date: "2019-09-02",
    summary: "Building a typewriter text effect with async generators.",
    url: "https://dev.to/kapantzak/creating-the-typewriter-effect-with-the-use-of-async-generators-5f1e",
    source: "DEV.TO",
  },
  {
    title: "Using Redux in a legacy ASP.NET Web Forms project",
    date: "2019-08-22",
    summary:
      "Bringing Redux state management into a legacy ASP.NET Web Forms application.",
    url: "https://dev.to/kapantzak/using-redux-in-a-legacy-asp-net-web-forms-project-1805",
    source: "DEV.TO",
  },
  {
    title: "Waiting for visible element",
    date: "2019-08-19",
    summary:
      "Running code only once a specific element becomes visible on the page.",
    url: "https://dev.to/kapantzak/waiting-for-visible-element-4ck9",
    source: "DEV.TO",
  },
  {
    title: "JS illustrated: The event loop 🔁",
    date: "2019-08-15",
    summary:
      "An illustrated explanation of how the event loop lets single-threaded JavaScript run asynchronous code.",
    url: "https://dev.to/kapantzak/js-illustrated-the-event-loop-4mco",
    source: "DEV.TO",
  },
  {
    title: "Some of my favorite Javascript resources",
    date: "2019-08-06",
    summary: "A list of the JavaScript resources I keep coming back to.",
    url: "https://dev.to/kapantzak/some-of-my-favorite-javascript-resources-13cg",
    source: "DEV.TO",
  },
];
